# Generated by Django 4.2.25 on 2025-10-11 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_phone_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='pay_create_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
